name: product_list
description: A manager for products.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^3.1.17
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  firebase_core: ^1.17.1
  firebase_image: ^1.1.1
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  intl: ^0.17.0

dev_dependencies:
  build_runner: ^2.1.10
  fake_cloud_firestore: ^1.2.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.2.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/data.json